thread = 8
logger = nil
harbor = 0
start = "main"
bootstrap = "snlua bootstrap"	-- The service for bootstrap
luaservice = "./service/?.lua;./examples/login/?.lua"
lualoader = "lualib/loader.lua"
lua_path = "./lualib/?.lua;".."./lualib/?/init.lua;".."./examples/?.lua"
cpath = "./cservice/?.so"
